### PR TITLE
refactor: add missing frozen string literal comment

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by n-rodriguez** [comment]
ping @thde

**Comment by n-rodriguez** [comment]
@thde you forgot this one 😄

**Comment by n-rodriguez** [comment]
@thde I think you should read this https://gist.github.com/fxn/bf4eed2505c76f4fca03ab48c43adc72

**Comment by n-rodriguez** [comment]
@thde The error in CI has nothing to do with this PR.

This PR revealed a bug in the gem : https://github.com/ninech/netbox-client-ruby/pull/78/files#diff-45ae662d8aec8fb27659072ad06e7830118ef3d5ed4a4df0c0f2f1f812056a1e

**Comment by thde** [comment]
Cache is cleared, but it still shows the same error and seems to pull something.

```
❯ gh cache list
No caches found in ninech/netbox-client-ruby
```

As it works in the default branch, this leads me to believe, that Github Actions may associate the cache to your repository. Would you mind trying to clear the caches in your fork?

**Comment by n-rodriguez** [comment]
> As it works in the default branch, this leads me to believe, that Github Actions may associate the cache to your repository. Would you mind trying to clear the caches in your fork?

done!

```sh
> gh cache list
No caches found in n-rodriguez/netbox-client-ruby
```

**Review by thde — APPROVED** [review]

**Pull request merged**
