### PR TITLE
Add IPAM Services entries

### PR DESCRIPTION
**Pull request by fkshom**
Add basic IPAM Services Entries functionality.

### CODE REVIEW

**Comment by fkshom** [comment]
Any updates?

Please let me know if there is anything I can do.

**Comment by thde** [comment]
The tests weren't running in the pipeline. Would you mind doing a rebase from the default branch? Thanks.

**Comment by fkshom** [comment]
Thank you for your reply. Rebased to default branch.

**Review by thde — APPROVED** [review]

**Comment by thde** [comment]
New version has been released:
https://github.com/ninech/netbox-client-ruby/releases/tag/v0.9.0

**Comment by fkshom** [comment]
@thde Thank you so much!

**Pull request merged**
