### PR TITLE
Add Tag entity and relate it to Device

### PR DESCRIPTION
**Pull request by jlemesh**
Add Tag entity and relate it to Device (i. e. Tags can be fetched separately and with Device).

Resolves https://github.com/ninech/netbox-client-ruby/issues/46

### CODE REVIEW

**Comment by jlemesh** [comment]
Hmm, how do I poke anybody here?

**Review by thde — APPROVED** [review]
Thanks for the PR!

**Comment by thde** [comment]
released

**Comment by jlemesh** [comment]
Fantastic, thank you!

**Pull request merged**
