### PR TITLE
refactor: use zeitwerk to load gem files

### PR DESCRIPTION
**Pull request by n-rodriguez**
This PR is based on https://github.com/ninech/netbox-client-ruby/pull/86, 

You'll need to merge https://github.com/ninech/netbox-client-ruby/pull/86 first

### CODE REVIEW

**Comment by n-rodriguez** [comment]
You need to purge GithubActions cache for this to work.

It works perfectly on my side : https://github.com/n-rodriguez/netbox-client-ruby/actions/runs/11463755090

**Comment by n-rodriguez** [comment]
@thde if you purge GithubActions cache it should work now

**Review by thde — DISMISSED** [review]

**Comment by thde** [comment]
@n-rodriguez could you rebase one more time?

**Comment by n-rodriguez** [comment]
> @n-rodriguez could you rebase one more time?

done!

**Review by thde — APPROVED** [review]

**Pull request merged**
